#!/bin/sh
# template-version: 4
# Generated by ocafitsfiles.render_download_script()
# User: $username | Date: $generated_date | Files: $n_files

API_ENDPOINT="$api_endpoint"
AUTH_ENDPOINT="$auth_endpoint"
USERNAME="$username"
EXPIRES_IN="$expires_in"
DL_TIMEOUT="$dl_timeout"

API_TOKEN=""
TOKEN_TIME=0
PASSWORD=""

PROG="$$(basename "$$0")"

err()  { printf '%s\n' "$$*" >&2; }

usage() {
  cat <<EOF
$$PROG — OCADB download script
Generated for user "$$USERNAME" on $generated_date ($n_files file(s)).
Source: OCM Observatory Archive (OCADB)

Usage:
  $$PROG -l
      List filenames (first column of active rows).

  $$PROG -L
      Print full embedded data table (including comments).

  $$PROG [-p PASSWORD] -c
      Check file availability in object store (no download).

  $$PROG [-p PASSWORD] -d [DIR]
      Download missing files into DIR (default: current directory).

  $$PROG [-p PASSWORD] -D [DIR]
      Download into DIR, overwriting existing files.

  $$PROG -h
      Show this help.

Password resolution (first match wins):
  1. -p PASSWORD option
  2. \$$OCADB_PASSWORD environment variable
  3. Interactive prompt

To download a subset of files, copy this script and edit the file
list at the end of the script (after the __DATA__ marker).
EOF
}

die_usage() { usage >&2; exit 2; }

ensure_tools() {
  if command -v curl >/dev/null 2>&1; then
    DL_TOOL="curl"
  elif command -v wget >/dev/null 2>&1; then
    DL_TOOL="wget"
  else
    err "ERROR: neither curl nor wget found"
    exit 1
  fi
}

data_lines() {
  # Print everything after the terminal __DATA__ marker.
  sed '1,/^__DATA__$$/d' "$$0"
}

active_lines() {
  # Filter out blank/comment lines from embedded table
  data_lines | sed '/^[[:space:]]*#/d;/^[[:space:]]*$$/d'
}

now_epoch() { date +%s; }

strip_quotes() {
  # Remove surrounding double quotes from API response
  sed 's/^"//;s/"$$//'
}

# --- Authentication ---

resolve_password() {
  # Set PASSWORD from -p arg, env var, or interactive prompt.
  [ -n "$$PASSWORD" ] && return 0

  if [ -n "$${OCADB_PASSWORD:-}" ]; then
    PASSWORD="$$OCADB_PASSWORD"
    return 0
  fi

  # Interactive prompt (hide input)
  printf 'Password for user "%s": ' "$$USERNAME" >&2
  stty -echo 2>/dev/null
  IFS= read -r PASSWORD
  stty echo 2>/dev/null
  printf '\n' >&2

  if [ -z "$$PASSWORD" ]; then
    err "ERROR: no password provided"
    exit 1
  fi
}

login() {
  # Authenticate against AUTH_ENDPOINT; sets API_TOKEN and TOKEN_TIME.
  # The plaintoken endpoint returns a bare JWT string (no JSON, no quotes).
  _tok=""
  if [ "$$DL_TOOL" = "curl" ]; then
    _tok="$$(curl -fsS --max-time "$$DL_TIMEOUT" \
      -X POST \
      -H "Content-Type: application/x-www-form-urlencoded" \
      -H "Authorization: Bearer" \
      --data-urlencode "username=$$USERNAME" \
      --data-urlencode "password=$$PASSWORD" \
      --data-urlencode "grant_type=password" \
      "$$AUTH_ENDPOINT" 2>/dev/null)"
  else
    _payload="username=$$(printf '%s' "$$USERNAME" | sed 's/[^a-zA-Z0-9._~-]/%&/g')&password=$$(printf '%s' "$$PASSWORD" | sed 's/[^a-zA-Z0-9._~-]/%&/g')&grant_type=password"
    _tok="$$(wget -qO- --timeout="$$DL_TIMEOUT" \
      --header="Content-Type: application/x-www-form-urlencoded" \
      --header="Authorization: Bearer" \
      --post-data="$$_payload" \
      "$$AUTH_ENDPOINT" 2>/dev/null)"
  fi

  if [ -z "$$_tok" ]; then
    err "ERROR: authentication failed (empty response from $$AUTH_ENDPOINT)"
    return 1
  fi

  API_TOKEN="$$_tok"
  TOKEN_TIME="$$(now_epoch)"
  return 0
}

ensure_token() {
  # Re-login if token is empty or older than 25 minutes (1500 s).
  if [ -z "$$API_TOKEN" ]; then
    login || { err "ERROR: login failed"; exit 1; }
    return 0
  fi
  _now="$$(now_epoch)"
  _age=$$((_now - TOKEN_TIME))
  if [ "$$_age" -ge 1500 ]; then
    login || { err "ERROR: token refresh failed"; exit 1; }
  fi
}

# --- Presigned URL & download helpers ---

fetch_presigned_url() {
  # GET {API_ENDPOINT}/by-filename/{key}/plainurl?expires_in={EXPIRES_IN}
  # Return codes:
  #   0  success (url on stdout)
  #  44  key not found in API (404)
  #  41  unauthorized (401, token expired)
  #  >0  other error
  key="$$1"
  _body=""
  _http_code=""

  if [ "$$DL_TOOL" = "curl" ]; then
    _body="$$(curl -sS -w '\n__HTTP_CODE__:%{http_code}' -X GET --max-time "$$DL_TIMEOUT" \
      -H "Authorization: Bearer $$API_TOKEN" \
      -H "Content-Type: application/json" \
      --data '' \
      "$$API_ENDPOINT/by-filename/$$key/plainurl?expires_in=$$EXPIRES_IN" 2>/dev/null)"
    _rc=$$?
  else
    # wget doesn't give us HTTP code easily; fallback to simpler detection
    _body="$$(wget -qO- --timeout="$$DL_TIMEOUT" \
      --header="Authorization: Bearer $$API_TOKEN" \
      --header="Content-Type: application/json" \
      "$$API_ENDPOINT/by-filename/$$key/plainurl?expires_in=$$EXPIRES_IN" 2>/dev/null)"
    _rc=$$?
  fi

  [ $$_rc -eq 0 ] || return 11

  # Extract HTTP code from curl footer
  _http_code="$$(printf '%s' "$$_body" | grep '^__HTTP_CODE__:' | sed 's/^__HTTP_CODE__://')"
  _body="$$(printf '%s' "$$_body" | sed '/^__HTTP_CODE__:/d')"

  [ -n "$$_body" ] || return 12

  # Check HTTP status
  case "$$_http_code" in
    401) return 41 ;;
    404) return 44 ;;
  esac

  # API detail='... not found' for unknown filenames
  if printf '%s' "$$_body" | grep -qi 'not found'; then
    return 44
  fi

  _url="$$(printf '%s' "$$_body" | strip_quotes)"
  case "$$_url" in
    http://*|https://*)
      printf '%s' "$$_url"
      return 0
      ;;
  esac

  return 13
}

fetch_presigned_url_with_retry() {
  # Fetch presigned URL; retry once after re-login ONLY on 401.
  # Return codes:
  #   0  success
  #  44  key not found in API
  #  45  object missing in store
  #  >0  other failure
  _key="$$1"
  _url="$$(fetch_presigned_url "$$_key" 2>/dev/null)"
  _rc=$$?
  if [ $$_rc -eq 0 ] && [ -n "$$_url" ]; then
    printf '%s' "$$_url"
    return 0
  fi
  if [ $$_rc -eq 44 ]; then
    return 44
  fi

  # Retry ONLY on 401 (token expired)
  if [ $$_rc -ne 41 ]; then
    return $$_rc
  fi

  login || return 21
  _url="$$(fetch_presigned_url "$$_key" 2>/dev/null)"
  _rc=$$?
  if [ $$_rc -eq 0 ] && [ -n "$$_url" ]; then
    printf '%s' "$$_url"
    return 0
  fi
  if [ $$_rc -eq 44 ]; then
    return 44
  fi

  return $$_rc
}

check_object_exists() {
  # Verify object is accessible via a minimal GET (1 byte).
  # HEAD is not used because some S3-compatible stores (e.g. Backblaze B2)
  # reject HEAD on presigned URLs signed for GET only.
  # Return: 0 if exists, 45 if missing in store
  url="$$1"
  if [ "$$DL_TOOL" = "curl" ]; then
    curl -fsSo /dev/null -r 0-0 --max-time "$$DL_TIMEOUT" "$$url" 2>/dev/null && return 0
    return 45
  else
    wget -qO /dev/null --header="Range: bytes=0-0" --timeout="$$DL_TIMEOUT" "$$url" 2>/dev/null && return 0
    return 45
  fi
}

download_part_then_rename() {
  # $$1 url, $$2 final path
  url="$$1"
  final="$$2"
  part="$${final}.part"

  d="$$(dirname "$$final")"
  [ -d "$$d" ] || mkdir -p "$$d" || return 11

  [ -f "$$part" ] && rm -f "$$part" >/dev/null 2>&1

  if [ "$$DL_TOOL" = "curl" ]; then
    curl -fSL --max-time "$$DL_TIMEOUT" -o "$$part" "$$url" >/dev/null 2>&1 || return 12
  else
    wget -q --timeout="$$DL_TIMEOUT" -O "$$part" "$$url" >/dev/null 2>&1 || return 12
  fi

  mv -f "$$part" "$$final" >/dev/null 2>&1 || return 13
  return 0
}

# --- CLI parsing ---
if [ $$# -eq 0 ]; then
  die_usage
fi

MODE=""
OUT_DIR="."
OVERWRITE=0

# Parse -p PASSWORD if given as first argument pair
if [ "$$1" = "-p" ]; then
  if [ $$# -lt 2 ]; then
    err "ERROR: -p requires a password argument"
    exit 2
  fi
  PASSWORD="$$2"
  shift 2
fi

if [ $$# -eq 0 ]; then
  die_usage
fi

case "$$1" in
  -l) MODE="list_keys" ;;
  -L) MODE="list_table" ;;
  -c) MODE="check" ;;
  -d)
    MODE="download"; OVERWRITE=0
    [ $$# -ge 2 ] && [ "$${2#-}" = "$$2" ] && OUT_DIR="$$2"
    ;;
  -D)
    MODE="download"; OVERWRITE=1
    [ $$# -ge 2 ] && [ "$${2#-}" = "$$2" ] && OUT_DIR="$$2"
    ;;
  -h|--help) usage; exit 0 ;;
  *) die_usage ;;
esac

# Tooling required for check/download
if [ "$$MODE" = "check" ] || [ "$$MODE" = "download" ]; then
  ensure_tools
  resolve_password
  login || { err "ERROR: initial login failed"; exit 1; }
fi

_cnt="$$(mktemp)" || { err "ERROR: cannot create temp file"; exit 1; }
printf '0 0 0\n' > "$$_cnt"
trap 'rm -f "$$_cnt"' EXIT

if [ "$$MODE" = "list_table" ]; then
  data_lines
  rm -f "$$_cnt"
  exit 0
fi

if [ "$$MODE" = "list_keys" ]; then
  active_lines | while IFS= read -r line; do
    # shellcheck disable=SC2086
    set -- $$line
    key="$$1"
    [ -n "$$key" ] && printf '%s\n' "$$key"
  done
  rm -f "$$_cnt"
  exit 0
fi

if [ "$$MODE" = "download" ]; then
  [ -d "$$OUT_DIR" ] || mkdir -p "$$OUT_DIR" || { err "ERROR: cannot create dir: $$OUT_DIR"; exit 1; }
fi

active_lines | while IFS= read -r line; do
  # shellcheck disable=SC2086
  set -- $$line
  key="$$1"
  [ -n "$$key" ] || continue

  # Read current counters
  read _ok _fail _skip < "$$_cnt"

  final="$$OUT_DIR/$$key"

  if [ "$$MODE" = "download" ]; then
    if [ -f "$$final" ] && [ "$$OVERWRITE" -ne 1 ]; then
      _skip=$$((_skip + 1))
      printf '%s %s %s\n' "$$_ok" "$$_fail" "$$_skip" > "$$_cnt"
      continue
    fi

    ensure_token
    start="$$(now_epoch)"
    printf 'Downloading %s ... ' "$$key"

    url="$$(fetch_presigned_url_with_retry "$$key")"
    rc=$$?
    if [ $$rc -ne 0 ] || [ -z "$$url" ]; then
      if [ $$rc -eq 44 ]; then
        printf 'NOT FOUND IN DB\n'
      else
        printf 'FAILED\n'
        err "ERROR: request failed for '$$key' (rc=$$rc)"
      fi
      _fail=$$((_fail + 1))
      printf '%s %s %s\n' "$$_ok" "$$_fail" "$$_skip" > "$$_cnt"
      continue
    fi

    if download_part_then_rename "$$url" "$$final"; then
      end="$$(now_epoch)"
      dur=$$((end - start))
      printf 'DONE in %ss\n' "$$dur"
      _ok=$$((_ok + 1))
    else
      dlrc=$$?
      if [ $$dlrc -eq 45 ]; then
        printf 'NOT FOUND IN STORE\n'
      else
        printf 'FAILED\n'
        err "ERROR: download from object store failed for '$$key' (rc=$$dlrc)"
      fi
      rm -f "$${final}.part" >/dev/null 2>&1
      _fail=$$((_fail + 1))
    fi

  elif [ "$$MODE" = "check" ]; then
    ensure_token
    url="$$(fetch_presigned_url_with_retry "$$key")"
    rc=$$?
    if [ $$rc -ne 0 ] || [ -z "$$url" ]; then
      if [ $$rc -eq 44 ]; then
        printf '%s  NOT FOUND IN DB\n' "$$key"
      else
        printf '%s  FAILED\n' "$$key"
        err "ERROR: request failed for '$$key' (rc=$$rc)"
      fi
      _fail=$$((_fail + 1))
      printf '%s %s %s\n' "$$_ok" "$$_fail" "$$_skip" > "$$_cnt"
      continue
    fi

    check_object_exists "$$url"
    _check_rc=$$?
    if [ $$_check_rc -eq 0 ]; then
      printf '%s  OK\n' "$$key"
      _ok=$$((_ok + 1))
    elif [ $$_check_rc -eq 45 ]; then
      printf '%s  NOT FOUND IN STORE\n' "$$key"
      _fail=$$((_fail + 1))
    else
      printf '%s  FAILED\n' "$$key"
      err "ERROR: object check failed for '$$key'"
      _fail=$$((_fail + 1))
    fi
  fi

  printf '%s %s %s\n' "$$_ok" "$$_fail" "$$_skip" > "$$_cnt"
done

# Read final counters
read ok fail skip < "$$_cnt"
rm -f "$$_cnt"
trap - EXIT

# Summary for check/download (minimal)
if [ "$$MODE" = "check" ]; then
  printf 'Finished. ok=%s fail=%s\n' "$$ok" "$$fail"
  [ "$$fail" -eq 0 ]
elif [ "$$MODE" = "download" ]; then
  printf 'Finished. ok=%s fail=%s skip=%s\n' "$$ok" "$$fail" "$$skip"
  [ "$$fail" -eq 0 ]
fi

exit 0

__DATA__
$data_block
