#!/bin/sh
# template-version: 3
# Generated by ocafitsfiles.render_download_script()

API_ENDPOINT="$api_endpoint"
API_TOKEN="$api_token"
EXPIRES_IN="$expires_in"
DL_TIMEOUT="$dl_timeout"

PROG="$$(basename "$$0")"

err()  { printf '%s\n' "$$*" >&2; }

usage() {
  cat <<EOF
$$PROG - fetch/check files via presigned URLs (embedded data table)

Usage:
  $$PROG -l
      Print raw list (first column only) for active (non-comment) rows.

  $$PROG -L
      Print full embedded table, including commented rows.

  $$PROG -c
      Check existence in object store via HEAD (no download).

  $$PROG -d [DIR]
      Download only missing files into DIR (default: .)

  $$PROG -D [DIR]
      Download into DIR and overwrite if exists.

Notes:
  - Active rows are non-empty lines not starting with '#'.
  - First column (filename/key) must NOT contain spaces.
  - One-line success output:
      Downloading <key> ... DONE in <Ns>
EOF
}

die_usage() { usage >&2; exit 2; }

ensure_tools() {
  if command -v curl >/dev/null 2>&1; then
    DL_TOOL="curl"
  elif command -v wget >/dev/null 2>&1; then
    DL_TOOL="wget"
  else
    err "ERROR: neither curl nor wget found"
    exit 1
  fi
}

data_lines() {
  # Embedded data table (heredoc — safe for sh -n)
  cat <<'__DATA__'
$data_block
__DATA__
}

active_lines() {
  # Filter out blank/comment lines from embedded table
  data_lines | sed '/^[[:space:]]*#/d;/^[[:space:]]*$$/d'
}

now_epoch() { date +%s; }

strip_quotes() {
  # Remove surrounding double quotes from API response
  sed 's/^"//;s/"$$//'
}

fetch_presigned_url() {
  # GET {API_ENDPOINT}/by-filename/{key}/plainurl?expires_in={EXPIRES_IN}
  key="$$1"

  if [ "$$DL_TOOL" = "curl" ]; then
    curl -fsS -X GET --max-time "$$DL_TIMEOUT" \
      -H "Authorization: Bearer $$API_TOKEN" \
      -H "Content-Type: application/json" \
      --data '' \
      "$$API_ENDPOINT/by-filename/$$key/plainurl?expires_in=$$EXPIRES_IN" \
      | strip_quotes
  else
    wget -qO- --timeout="$$DL_TIMEOUT" \
      --header="Authorization: Bearer $$API_TOKEN" \
      --header="Content-Type: application/json" \
      "$$API_ENDPOINT/by-filename/$$key/plainurl?expires_in=$$EXPIRES_IN" \
      | strip_quotes
  fi
}

check_object_exists() {
  # Verify object is accessible via a minimal GET (1 byte).
  # HEAD is not used because some S3-compatible stores (e.g. Backblaze B2)
  # reject HEAD on presigned URLs signed for GET only.
  url="$$1"
  if [ "$$DL_TOOL" = "curl" ]; then
    curl -fsSo /dev/null -r 0-0 --max-time "$$DL_TIMEOUT" "$$url" 2>/dev/null
  else
    wget -qO /dev/null --header="Range: bytes=0-0" --timeout="$$DL_TIMEOUT" "$$url" 2>/dev/null
  fi
}

download_part_then_rename() {
  # $$1 url, $$2 final path
  url="$$1"
  final="$$2"
  part="$${final}.part"

  d="$$(dirname "$$final")"
  [ -d "$$d" ] || mkdir -p "$$d" || return 11

  [ -f "$$part" ] && rm -f "$$part" >/dev/null 2>&1

  if [ "$$DL_TOOL" = "curl" ]; then
    curl -fSL --max-time "$$DL_TIMEOUT" -o "$$part" "$$url" >/dev/null 2>&1 || return 12
  else
    wget -q --timeout="$$DL_TIMEOUT" -O "$$part" "$$url" >/dev/null 2>&1 || return 12
  fi

  mv -f "$$part" "$$final" >/dev/null 2>&1 || return 13
  return 0
}

# --- CLI parsing ---
if [ $$# -eq 0 ]; then
  die_usage
fi

MODE=""
OUT_DIR="."
OVERWRITE=0

case "$$1" in
  -l) MODE="list_keys" ;;
  -L) MODE="list_table" ;;
  -c) MODE="check" ;;
  -d)
    MODE="download"; OVERWRITE=0
    [ $$# -ge 2 ] && [ "$${2#-}" = "$$2" ] && OUT_DIR="$$2"
    ;;
  -D)
    MODE="download"; OVERWRITE=1
    [ $$# -ge 2 ] && [ "$${2#-}" = "$$2" ] && OUT_DIR="$$2"
    ;;
  -h|--help) usage; exit 0 ;;
  *) die_usage ;;
esac

# Tooling required for check/download
if [ "$$MODE" = "check" ] || [ "$$MODE" = "download" ]; then
  ensure_tools
fi

_cnt="$$(mktemp)" || { err "ERROR: cannot create temp file"; exit 1; }
printf '0 0 0\n' > "$$_cnt"
trap 'rm -f "$$_cnt"' EXIT

if [ "$$MODE" = "list_table" ]; then
  data_lines
  rm -f "$$_cnt"
  exit 0
fi

if [ "$$MODE" = "list_keys" ]; then
  active_lines | while IFS= read -r line; do
    # shellcheck disable=SC2086
    set -- $$line
    key="$$1"
    [ -n "$$key" ] && printf '%s\n' "$$key"
  done
  rm -f "$$_cnt"
  exit 0
fi

if [ "$$MODE" = "download" ]; then
  [ -d "$$OUT_DIR" ] || mkdir -p "$$OUT_DIR" || { err "ERROR: cannot create dir: $$OUT_DIR"; exit 1; }
fi

active_lines | while IFS= read -r line; do
  # shellcheck disable=SC2086
  set -- $$line
  key="$$1"
  [ -n "$$key" ] || continue

  # Read current counters
  read _ok _fail _skip < "$$_cnt"

  final="$$OUT_DIR/$$key"

  if [ "$$MODE" = "download" ]; then
    if [ -f "$$final" ] && [ "$$OVERWRITE" -ne 1 ]; then
      _skip=$$((_skip + 1))
      printf '%s %s %s\n' "$$_ok" "$$_fail" "$$_skip" > "$$_cnt"
      continue
    fi

    start="$$(now_epoch)"
    printf 'Downloading %s ... ' "$$key"

    url="$$(fetch_presigned_url "$$key" 2>/dev/null)"
    rc=$$?
    if [ $$rc -ne 0 ] || [ -z "$$url" ]; then
      printf '\n'
      err "ERROR: API failed for '$$key' (rc=$$rc)"
      _fail=$$((_fail + 1))
      printf '%s %s %s\n' "$$_ok" "$$_fail" "$$_skip" > "$$_cnt"
      continue
    fi

    if download_part_then_rename "$$url" "$$final"; then
      end="$$(now_epoch)"
      dur=$$((end - start))
      printf 'DONE in %ss\n' "$$dur"
      _ok=$$((_ok + 1))
    else
      dlrc=$$?
      printf '\n'
      err "ERROR: download failed for '$$key' (rc=$$dlrc)"
      rm -f "$${final}.part" >/dev/null 2>&1
      _fail=$$((_fail + 1))
    fi

  elif [ "$$MODE" = "check" ]; then
    url="$$(fetch_presigned_url "$$key" 2>/dev/null)"
    rc=$$?
    if [ $$rc -ne 0 ] || [ -z "$$url" ]; then
      err "ERROR: API failed for '$$key' (rc=$$rc)"
      _fail=$$((_fail + 1))
      printf '%s %s %s\n' "$$_ok" "$$_fail" "$$_skip" > "$$_cnt"
      continue
    fi

    if check_object_exists "$$url"; then
      printf 'OK %s\n' "$$key"
      _ok=$$((_ok + 1))
    else
      err "MISSING $$key"
      _fail=$$((_fail + 1))
    fi
  fi

  printf '%s %s %s\n' "$$_ok" "$$_fail" "$$_skip" > "$$_cnt"
done

# Read final counters
read ok fail skip < "$$_cnt"
rm -f "$$_cnt"
trap - EXIT

# Summary for check/download (minimal)
if [ "$$MODE" = "check" ]; then
  printf 'Finished. ok=%s fail=%s\n' "$$ok" "$$fail"
  [ "$$fail" -eq 0 ]
elif [ "$$MODE" = "download" ]; then
  printf 'Finished. ok=%s fail=%s skip=%s\n' "$$ok" "$$fail" "$$skip"
  [ "$$fail" -eq 0 ]
fi

exit 0

